import { createResource, splitProps, type JSX } from 'solid-js';
import AlertCircleSvg from '@phosphor-icons/core/assets/regular/warning-circle.svg?raw';
import ArrowLeftSvg from '@phosphor-icons/core/assets/regular/arrow-left.svg?raw';
import ArrowLeftFromLineSvg from '@phosphor-icons/core/assets/regular/sign-out.svg?raw';
import BoldSvg from '@phosphor-icons/core/assets/regular/text-b.svg?raw';
import CheckSvg from '@phosphor-icons/core/assets/regular/check.svg?raw';
import CheckCircle2Svg from '@phosphor-icons/core/assets/regular/check-circle.svg?raw';
import ChevronDownSvg from '@phosphor-icons/core/assets/regular/caret-down.svg?raw';
import ChevronRightSvg from '@phosphor-icons/core/assets/regular/caret-right.svg?raw';
import CodeSvg from '@phosphor-icons/core/assets/regular/code.svg?raw';
import CopySvg from '@phosphor-icons/core/assets/regular/copy.svg?raw';
import ExternalLinkSvg from '@phosphor-icons/core/assets/regular/arrow-square-out.svg?raw';
import EyeSvg from '@phosphor-icons/core/assets/regular/eye.svg?raw';
import EyeOffSvg from '@phosphor-icons/core/assets/regular/eye-slash.svg?raw';
import FileCodeSvg from '@phosphor-icons/core/assets/regular/file-code.svg?raw';
import FileTextSvg from '@phosphor-icons/core/assets/regular/file-text.svg?raw';
import FolderSvg from '@phosphor-icons/core/assets/regular/folder.svg?raw';
import GitBranchSvg from '@phosphor-icons/core/assets/regular/git-branch.svg?raw';
import GripVerticalSvg from '@phosphor-icons/core/assets/regular/dots-six-vertical.svg?raw';
import HammerSvg from '@phosphor-icons/core/assets/regular/hammer.svg?raw';
import Heading2Svg from '@phosphor-icons/core/assets/regular/text-h-two.svg?raw';
import Heading3Svg from '@phosphor-icons/core/assets/regular/text-h-three.svg?raw';
import HistorySvg from '@phosphor-icons/core/assets/regular/clock-counter-clockwise.svg?raw';
import HouseSvg from '@phosphor-icons/core/assets/regular/house.svg?raw';
import ImagePlusSvg from '@phosphor-icons/core/assets/regular/image.svg?raw';
import ImagesSvg from '@phosphor-icons/core/assets/regular/images.svg?raw';
import InfoSvg from '@phosphor-icons/core/assets/regular/info.svg?raw';
import ItalicSvg from '@phosphor-icons/core/assets/regular/text-italic.svg?raw';
import LayersSvg from '@phosphor-icons/core/assets/regular/stack.svg?raw';
import Link2Svg from '@phosphor-icons/core/assets/regular/link.svg?raw';
import ListSvg from '@phosphor-icons/core/assets/regular/list.svg?raw';
import ListOrderedSvg from '@phosphor-icons/core/assets/regular/list-numbers.svg?raw';
import ListTreeSvg from '@phosphor-icons/core/assets/regular/tree-structure.svg?raw';
import MenuSvg from '@phosphor-icons/core/assets/regular/list.svg?raw';
import MinusSvg from '@phosphor-icons/core/assets/regular/minus.svg?raw';
import MoreHorizontalSvg from '@phosphor-icons/core/assets/regular/dots-three.svg?raw';
import PaintbrushVerticalSvg from '@phosphor-icons/core/assets/regular/paint-brush.svg?raw';
import PaletteSvg from '@phosphor-icons/core/assets/regular/palette.svg?raw';
import PencilSvg from '@phosphor-icons/core/assets/regular/pencil-simple.svg?raw';
import PlusSvg from '@phosphor-icons/core/assets/regular/plus.svg?raw';
import QuoteSvg from '@phosphor-icons/core/assets/regular/quotes.svg?raw';
import Redo2Svg from '@phosphor-icons/core/assets/regular/arrow-bend-up-right.svg?raw';
import RotateCcwSvg from '@phosphor-icons/core/assets/regular/arrow-counter-clockwise.svg?raw';
import SearchSvg from '@phosphor-icons/core/assets/regular/magnifying-glass.svg?raw';
import SettingsSvg from '@phosphor-icons/core/assets/regular/gear.svg?raw';
import SmartphoneSvg from '@phosphor-icons/core/assets/regular/device-mobile.svg?raw';
import SquareCodeSvg from '@phosphor-icons/core/assets/regular/code-block.svg?raw';
import StrikethroughSvg from '@phosphor-icons/core/assets/regular/text-strikethrough.svg?raw';
import TableSvg from '@phosphor-icons/core/assets/regular/table.svg?raw';
import Trash2Svg from '@phosphor-icons/core/assets/regular/trash.svg?raw';
import Undo2Svg from '@phosphor-icons/core/assets/regular/arrow-bend-up-left.svg?raw';
import UploadSvg from '@phosphor-icons/core/assets/regular/upload-simple.svg?raw';
import XSvg from '@phosphor-icons/core/assets/regular/x.svg?raw';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> { size?: number | string }
function SvgIcon(props: IconProps & { source: string }) {
  const [local, rest] = splitProps(props, ['source', 'size']);
  return <svg viewBox="0 0 256 256" fill="currentColor" width={local.size ?? 16} height={local.size ?? 16} aria-hidden="true" {...rest} innerHTML={local.source.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '')} />;
}

export const AlertCircle = (props: IconProps) => <SvgIcon source={AlertCircleSvg} {...props} />;
export const ArrowLeft = (props: IconProps) => <SvgIcon source={ArrowLeftSvg} {...props} />;
export const ArrowLeftFromLine = (props: IconProps) => <SvgIcon source={ArrowLeftFromLineSvg} {...props} />;
export const Bold = (props: IconProps) => <SvgIcon source={BoldSvg} {...props} />;
export const Check = (props: IconProps) => <SvgIcon source={CheckSvg} {...props} />;
export const CheckCircle2 = (props: IconProps) => <SvgIcon source={CheckCircle2Svg} {...props} />;
export const ChevronDown = (props: IconProps) => <SvgIcon source={ChevronDownSvg} {...props} />;
export const ChevronRight = (props: IconProps) => <SvgIcon source={ChevronRightSvg} {...props} />;
export const Code = (props: IconProps) => <SvgIcon source={CodeSvg} {...props} />;
export const Copy = (props: IconProps) => <SvgIcon source={CopySvg} {...props} />;
export const ExternalLink = (props: IconProps) => <SvgIcon source={ExternalLinkSvg} {...props} />;
export const Eye = (props: IconProps) => <SvgIcon source={EyeSvg} {...props} />;
export const EyeOff = (props: IconProps) => <SvgIcon source={EyeOffSvg} {...props} />;
export const FileCode = (props: IconProps) => <SvgIcon source={FileCodeSvg} {...props} />;
export const FileText = (props: IconProps) => <SvgIcon source={FileTextSvg} {...props} />;
export const Folder = (props: IconProps) => <SvgIcon source={FolderSvg} {...props} />;
export const GitBranch = (props: IconProps) => <SvgIcon source={GitBranchSvg} {...props} />;
export const GripVertical = (props: IconProps) => <SvgIcon source={GripVerticalSvg} {...props} />;
export const Hammer = (props: IconProps) => <SvgIcon source={HammerSvg} {...props} />;
export const Heading2 = (props: IconProps) => <SvgIcon source={Heading2Svg} {...props} />;
export const Heading3 = (props: IconProps) => <SvgIcon source={Heading3Svg} {...props} />;
export const History = (props: IconProps) => <SvgIcon source={HistorySvg} {...props} />;
export const House = (props: IconProps) => <SvgIcon source={HouseSvg} {...props} />;
export const ImagePlus = (props: IconProps) => <SvgIcon source={ImagePlusSvg} {...props} />;
export const Images = (props: IconProps) => <SvgIcon source={ImagesSvg} {...props} />;
export const Info = (props: IconProps) => <SvgIcon source={InfoSvg} {...props} />;
export const Italic = (props: IconProps) => <SvgIcon source={ItalicSvg} {...props} />;
export const Layers = (props: IconProps) => <SvgIcon source={LayersSvg} {...props} />;
export const Link2 = (props: IconProps) => <SvgIcon source={Link2Svg} {...props} />;
export const List = (props: IconProps) => <SvgIcon source={ListSvg} {...props} />;
export const ListOrdered = (props: IconProps) => <SvgIcon source={ListOrderedSvg} {...props} />;
export const ListTree = (props: IconProps) => <SvgIcon source={ListTreeSvg} {...props} />;
export const Menu = (props: IconProps) => <SvgIcon source={MenuSvg} {...props} />;
export const Minus = (props: IconProps) => <SvgIcon source={MinusSvg} {...props} />;
export const MoreHorizontal = (props: IconProps) => <SvgIcon source={MoreHorizontalSvg} {...props} />;
export const PaintbrushVertical = (props: IconProps) => <SvgIcon source={PaintbrushVerticalSvg} {...props} />;
export const Palette = (props: IconProps) => <SvgIcon source={PaletteSvg} {...props} />;
export const Pencil = (props: IconProps) => <SvgIcon source={PencilSvg} {...props} />;
export const Plus = (props: IconProps) => <SvgIcon source={PlusSvg} {...props} />;
export const Quote = (props: IconProps) => <SvgIcon source={QuoteSvg} {...props} />;
export const Redo2 = (props: IconProps) => <SvgIcon source={Redo2Svg} {...props} />;
export const RotateCcw = (props: IconProps) => <SvgIcon source={RotateCcwSvg} {...props} />;
export const Search = (props: IconProps) => <SvgIcon source={SearchSvg} {...props} />;
export const Settings = (props: IconProps) => <SvgIcon source={SettingsSvg} {...props} />;
export const Smartphone = (props: IconProps) => <SvgIcon source={SmartphoneSvg} {...props} />;
export const SquareCode = (props: IconProps) => <SvgIcon source={SquareCodeSvg} {...props} />;
export const Strikethrough = (props: IconProps) => <SvgIcon source={StrikethroughSvg} {...props} />;
export const Table = (props: IconProps) => <SvgIcon source={TableSvg} {...props} />;
export const Trash2 = (props: IconProps) => <SvgIcon source={Trash2Svg} {...props} />;
export const Undo2 = (props: IconProps) => <SvgIcon source={Undo2Svg} {...props} />;
export const Upload = (props: IconProps) => <SvgIcon source={UploadSvg} {...props} />;
export const X = (props: IconProps) => <SvgIcon source={XSvg} {...props} />;

// Only bundled Phosphor assets can be loaded; schema values never become markup.
const icons = import.meta.glob('/node_modules/@phosphor-icons/core/assets/regular/*.svg', { query: '?raw', import: 'default' });
export function ContentTypeIcon(props: IconProps & { name?: string }) {
  const [local, rest] = splitProps(props, ['name']);
  const [source] = createResource(() => local.name || 'file-text', async (name) => {
    const load = icons[`/node_modules/@phosphor-icons/core/assets/regular/${name}.svg`];
    return load ? await load() as string : FileTextSvg;
  });
  return <SvgIcon source={source.latest ?? FileTextSvg} {...rest} />;
}
