<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'li' . ( ' class="' . ('post-card') . '"' ) . '>' . ( '
  ' . ( '<' . 'a' . ( $eval->attribute( 'href', ( ( is_array( $__v2 = ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v1[ 'post' ] ?? null ) : $eval->getProperty( $__v1, 'post' ) ) ) ) ? ( $__v2[ 'url' ] ?? null ) : $eval->getProperty( $__v2, 'url' ) ) ) ) ) . '>' . ( $eval->renderValue( ( ( is_array( $__v4 = ( ( is_array( $__v3 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v3[ 'post' ] ?? null ) : $eval->getProperty( $__v3, 'post' ) ) ) ) ? ( $__v4[ 'title' ] ?? null ) : $eval->getProperty( $__v4, 'title' ) ) ), $ctx ) ) . '</' . 'a' . '>' ) . '
  ' . ( '<' . 'time' . ( $eval->attribute( 'datetime', ( ( is_array( $__v6 = ( ( is_array( $__v5 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v5[ 'post' ] ?? null ) : $eval->getProperty( $__v5, 'post' ) ) ) ) ? ( $__v6[ 'date' ] ?? null ) : $eval->getProperty( $__v6, 'date' ) ) ) ) ) . '>' . ( $eval->renderValue( ( ( is_array( $__v8 = ( ( is_array( $__v7 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v7[ 'post' ] ?? null ) : $eval->getProperty( $__v7, 'post' ) ) ) ) ? ( $__v8[ 'date' ] ?? null ) : $eval->getProperty( $__v8, 'date' ) ) ), $ctx ) ) . '</' . 'time' . '>' ) . '
  ' . ( $eval->truthy( ( ( is_array( $__v9 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v9[ 'excerpt' ] ?? null ) : $eval->getProperty( $__v9, 'excerpt' ) ) ) ) ? ( ( '<' . 'p' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v11 = ( ( is_array( $__v10 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v10[ 'post' ] ?? null ) : $eval->getProperty( $__v10, 'post' ) ) ) ) ? ( $__v11[ 'excerpt' ] ?? null ) : $eval->getProperty( $__v11, 'excerpt' ) ) ), $ctx ) ) . '</' . 'p' . '>' ) ) : '' ) . '
' ) . '</' . 'li' . '>' );
        $out .= '
';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};