<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'div' . ( ' class="' . ('wrap footer') . '"' ) . '>' . ( '
  ' . ( '<' . 'p' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v2 = ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v1[ 'settings' ] ?? null ) : $eval->getProperty( $__v1, 'settings' ) ) ) ) ? ( $__v2[ 'note' ] ?? null ) : $eval->getProperty( $__v2, 'note' ) ) ), $ctx ) ) . '</' . 'p' . '>' ) . '
  ' . ( '<' . 'p' . ( ' class="' . ('built') . '"' ) . '>' . ( 'Built with Pillar' ) . '</' . 'p' . '>' ) . '
' ) . '</' . 'div' . '>' );
        $out .= '

';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};