<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'article' . ( ' class="' . ('feature') . '"' ) . '>' . ( '
  ' . ( '<' . 'h3' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v3 = ( ( is_array( $__v2 = ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v1[ 'block' ] ?? null ) : $eval->getProperty( $__v1, 'block' ) ) ) ) ? ( $__v2[ 'settings' ] ?? null ) : $eval->getProperty( $__v2, 'settings' ) ) ) ) ? ( $__v3[ 'title' ] ?? null ) : $eval->getProperty( $__v3, 'title' ) ) ), $ctx ) ) . '</' . 'h3' . '>' ) . '
  ' . ( '<' . 'p' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v6 = ( ( is_array( $__v5 = ( ( is_array( $__v4 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'props' ) : $ctx->get( 'props' ) ) ) ) ? ( $__v4[ 'block' ] ?? null ) : $eval->getProperty( $__v4, 'block' ) ) ) ) ? ( $__v5[ 'settings' ] ?? null ) : $eval->getProperty( $__v5, 'settings' ) ) ) ) ? ( $__v6[ 'body' ] ?? null ) : $eval->getProperty( $__v6, 'body' ) ) ), $ctx ) ) . '</' . 'p' . '>' ) . '
' ) . '</' . 'article' . '>' );
        $out .= '
';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};