<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'article' . ( ' class="' . ('wrap prose') . '"' ) . '>' . ( '
  ' . ( '<' . 'h1' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v1[ 'title' ] ?? null ) : $eval->getProperty( $__v1, 'title' ) ) ), $ctx ) ) . '</' . 'h1' . '>' ) . '
  ' . ( $eval->truthy( ( $eval->truthy( $__v5 = ( ( is_array( $__v3 = ( ( is_array( $__v2 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v2[ 'settings' ] ?? null ) : $eval->getProperty( $__v2, 'settings' ) ) ) ) ? ( $__v3[ 'show_date' ] ?? null ) : $eval->getProperty( $__v3, 'show_date' ) ) ) ) ? ( ( is_array( $__v4 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v4[ 'date' ] ?? null ) : $eval->getProperty( $__v4, 'date' ) ) ) : $__v5 ) ) ? ( '
    ' . ( '<' . 'time' . ( $eval->attribute( 'datetime', ( ( is_array( $__v6 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v6[ 'date' ] ?? null ) : $eval->getProperty( $__v6, 'date' ) ) ) ) ) . '>' . ( $eval->renderValue( ( ( is_array( $__v7 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v7[ 'date' ] ?? null ) : $eval->getProperty( $__v7, 'date' ) ) ), $ctx ) ) . '</' . 'time' . '>' ) . '
  ' ) : '' ) . '
  ' . $eval->renderValue( ( ( is_array( $__v8 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v8[ 'content' ] ?? null ) : $eval->getProperty( $__v8, 'content' ) ) ), $ctx ) . '
' ) . '</' . 'article' . '>' );
        $out .= '

';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};