<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'div' . ( ' class="' . ('wrap header') . '"' ) . '>' . ( '
  ' . ( '<' . 'a' . ( ' class="' . ('brand') . '"' . ' href="' . ('/') . '"' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'site' ) : $ctx->get( 'site' ) ) ) ) ? ( $__v1[ 'title' ] ?? null ) : $eval->getProperty( $__v1, 'title' ) ) ), $ctx ) ) . '</' . 'a' . '>' ) . '
  ' . ( '<' . 'nav' . ( '' ) . '>' . ( '
    ' . ( $eval->mapJoin( ( $eval->methodCall( ( ( is_array( $__v3 = ( ( is_array( $__v2 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v2[ 'settings' ] ?? null ) : $eval->getProperty( $__v2, 'settings' ) ) ) ) ? ( $__v3[ 'links' ] ?? null ) : $eval->getProperty( $__v3, 'links' ) ) ), 'split', [ (',') ], $ctx ) ), (static function ( mixed ...$__args ) use ( $ctx, $eval ) {
    $__v4 = $__args[0] ?? null;
        return ( '<' . 'a' . ( $eval->attribute( 'href', ( $eval->methodCall( ( $eval->getProperty( ( $eval->methodCall( ( $__v4 ), 'split', [ ('|') ], $ctx ) ), (1) ) ), 'trim', [  ], $ctx ) ) ) ) . '>' . ( $eval->renderValue( ( $eval->methodCall( ( $eval->getProperty( ( $eval->methodCall( ( $__v4 ), 'split', [ ('|') ], $ctx ) ), (0) ) ), 'trim', [  ], $ctx ) ), $ctx ) ) . '</' . 'a' . '>' );
}), $ctx ) ) . '
  ' ) . '</' . 'nav' . '>' ) . '
' ) . '</' . 'div' . '>' );
        $out .= '

';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};