<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'div' . ( ' class="' . ('wrap hero') . '"' . ' style="' . ( 'padding-block:' . $eval->renderValue( ( ( is_array( $__v2 = ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v1[ 'settings' ] ?? null ) : $eval->getProperty( $__v1, 'settings' ) ) ) ) ? ( $__v2[ 'padding' ] ?? null ) : $eval->getProperty( $__v2, 'padding' ) ) ), $ctx ) . 'px;text-align:' . $eval->renderValue( ( ( is_array( $__v4 = ( ( is_array( $__v3 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v3[ 'settings' ] ?? null ) : $eval->getProperty( $__v3, 'settings' ) ) ) ) ? ( $__v4[ 'align' ] ?? null ) : $eval->getProperty( $__v4, 'align' ) ) ), $ctx ) ) . '"' ) . '>' . ( '
  ' . ( '<' . 'h1' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v6 = ( ( is_array( $__v5 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v5[ 'settings' ] ?? null ) : $eval->getProperty( $__v5, 'settings' ) ) ) ) ? ( $__v6[ 'heading' ] ?? null ) : $eval->getProperty( $__v6, 'heading' ) ) ), $ctx ) ) . '</' . 'h1' . '>' ) . '
  ' . ( '<' . 'p' . ( ' class="' . ('lede') . '"' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v8 = ( ( is_array( $__v7 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v7[ 'settings' ] ?? null ) : $eval->getProperty( $__v7, 'settings' ) ) ) ) ? ( $__v8[ 'subheading' ] ?? null ) : $eval->getProperty( $__v8, 'subheading' ) ) ), $ctx ) ) . '</' . 'p' . '>' ) . '
  ' . ( $eval->truthy( ( ( is_array( $__v10 = ( ( is_array( $__v9 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v9[ 'settings' ] ?? null ) : $eval->getProperty( $__v9, 'settings' ) ) ) ) ? ( $__v10[ 'cta_label' ] ?? null ) : $eval->getProperty( $__v10, 'cta_label' ) ) ) ) ? ( '
    ' . ( '<' . 'a' . ( ' class="' . ('button') . '"' . $eval->attribute( 'href', ( ( is_array( $__v12 = ( ( is_array( $__v11 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v11[ 'settings' ] ?? null ) : $eval->getProperty( $__v11, 'settings' ) ) ) ) ? ( $__v12[ 'cta_url' ] ?? null ) : $eval->getProperty( $__v12, 'cta_url' ) ) ) ) ) . '>' . ( $eval->renderValue( ( ( is_array( $__v14 = ( ( is_array( $__v13 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v13[ 'settings' ] ?? null ) : $eval->getProperty( $__v13, 'settings' ) ) ) ) ? ( $__v14[ 'cta_label' ] ?? null ) : $eval->getProperty( $__v14, 'cta_label' ) ) ), $ctx ) ) . '</' . 'a' . '>' ) . '
  ' ) : '' ) . '
' ) . '</' . 'div' . '>' );
        $out .= '

';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};