<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'div' . ( ' class="' . ('wrap features') . '"' ) . '>' . ( '
  ' . ( $eval->truthy( ( ( is_array( $__v2 = ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v1[ 'settings' ] ?? null ) : $eval->getProperty( $__v1, 'settings' ) ) ) ) ? ( $__v2[ 'heading' ] ?? null ) : $eval->getProperty( $__v2, 'heading' ) ) ) ) ? ( ( '<' . 'h2' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v4 = ( ( is_array( $__v3 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v3[ 'settings' ] ?? null ) : $eval->getProperty( $__v3, 'settings' ) ) ) ) ? ( $__v4[ 'heading' ] ?? null ) : $eval->getProperty( $__v4, 'heading' ) ) ), $ctx ) ) . '</' . 'h2' . '>' ) ) : '' ) . '
  ' . ( '<' . 'div' . ( ' class="' . ('grid') . '"' . ' style="' . ( '--columns:' . $eval->renderValue( ( ( is_array( $__v6 = ( ( is_array( $__v5 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v5[ 'settings' ] ?? null ) : $eval->getProperty( $__v5, 'settings' ) ) ) ) ? ( $__v6[ 'columns' ] ?? null ) : $eval->getProperty( $__v6, 'columns' ) ) ), $ctx ) ) . '"' ) . '>' . ( '
    ' . ( $eval->mapJoin( ( ( is_array( $__v7 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v7[ 'blocks' ] ?? null ) : $eval->getProperty( $__v7, 'blocks' ) ) ), (static function ( mixed ...$__args ) use ( $ctx, $eval ) {
    $__v8 = $__args[0] ?? null;
        return ( $eval->renderComponent( $ctx, 'Feature', $eval->mergeProps( $eval->mergeProps( [], ['block' => ( $__v8 )] ), [ 'children' => null, 'slots' => [] ] ) ) );
}), $ctx ) ) . '
  ' ) . '</' . 'div' . '>' ) . '
' ) . '</' . 'div' . '>' );
        $out .= '

';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};