<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $ctx->set( 'current', $__v1 = ( ( is_array( $__v0 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v0[ 'url' ] ?? null ) : $eval->getProperty( $__v0, 'url' ) ) ) );
        $__v2 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v2 ) {
            $out .= '<' . $__v2 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= ( '<' . 'div' . ( ' class="' . ('wrap docs') . '"' ) . '>' . ( '
  ' . ( '<' . 'aside' . ( ' class="' . ('docs-nav') . '"' ) . '>' . ( '
    ' . ( '<' . 'p' . ( ' class="' . ('docs-nav-title') . '"' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v4 = ( ( is_array( $__v3 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'section' ) : $ctx->get( 'section' ) ) ) ) ? ( $__v3[ 'settings' ] ?? null ) : $eval->getProperty( $__v3, 'settings' ) ) ) ) ? ( $__v4[ 'heading' ] ?? null ) : $eval->getProperty( $__v4, 'heading' ) ) ), $ctx ) ) . '</' . 'p' . '>' ) . '
    ' . ( '<' . 'ul' . ( '' ) . '>' . ( '
      ' . ( $eval->mapJoin( ( ( is_array( $__v6 = ( ( is_array( $__v5 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'collections' ) : $ctx->get( 'collections' ) ) ) ) ? ( $__v5[ 'docs' ] ?? null ) : $eval->getProperty( $__v5, 'docs' ) ) ) ) ? ( $__v6[ 'items' ] ?? null ) : $eval->getProperty( $__v6, 'items' ) ) ), (static function ( mixed ...$__args ) use ( $ctx, $eval, $__v1 ) {
    $__v7 = $__args[0] ?? null;
        return ( '<' . 'li' . ( '' ) . '>' . ( ( '<' . 'a' . ( $eval->attribute( 'href', ( ( is_array( $__v7 ) ? ( $__v7[ 'url' ] ?? null ) : $eval->getProperty( $__v7, 'url' ) ) ) ) . $eval->attribute( 'class', $eval->resolveClass( null, ['current' => ( ( ( is_array( $__v7 ) ? ( $__v7[ 'url' ] ?? null ) : $eval->getProperty( $__v7, 'url' ) ) ) === ( $__v1 ) )] ) ) ) . '>' . ( $eval->renderValue( ( ( is_array( $__v7 ) ? ( $__v7[ 'title' ] ?? null ) : $eval->getProperty( $__v7, 'title' ) ) ), $ctx ) ) . '</' . 'a' . '>' ) ) . '</' . 'li' . '>' );
}), $ctx ) ) . '
    ' ) . '</' . 'ul' . '>' ) . '
  ' ) . '</' . 'aside' . '>' ) . '
  ' . ( '<' . 'article' . ( ' class="' . ('prose docs-body') . '"' ) . '>' . ( '
    ' . ( '<' . 'h1' . ( '' ) . '>' . ( $eval->renderValue( ( ( is_array( $__v8 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v8[ 'title' ] ?? null ) : $eval->getProperty( $__v8, 'title' ) ) ), $ctx ) ) . '</' . 'h1' . '>' ) . '
    ' . $eval->renderValue( ( ( is_array( $__v9 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v9[ 'content' ] ?? null ) : $eval->getProperty( $__v9, 'content' ) ) ), $ctx ) . '
  ' ) . '</' . 'article' . '>' ) . '
' ) . '</' . 'div' . '>' );
        $out .= '

';
        if ( null !== $__v2 ) {
            $out .= '</' . $__v2 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};