<?php
declare(strict_types=1);

// Generated by Phpmystic\Liqx\Compiler — do not edit.
return static function ( \Phpmystic\Liqx\Context $ctx, \Phpmystic\Liqx\Evaluator $eval, ?array $wrapper = null ): string {
    $out = '';
    $ctx->push();
    try {
        $__v0 = ( null !== $wrapper && ! empty( $wrapper['tag'] ) && 'none' !== $wrapper['tag'] ) ? $wrapper['tag'] : null;
        if ( null !== $__v0 ) {
            $out .= '<' . $__v0 . $eval->formatWrapperAttrs( $wrapper['attrs'] ?? null ) . '>';
        }
        $out .= '<!doctype html>
';
        $out .= ( '<' . 'html' . ( ' lang="' . ('en') . '"' ) . '>' . ( '
' . ( '<' . 'head' . ( '' ) . '>' . ( '
  ' . ( '<' . 'meta' . ( ' charset="' . ('utf-8') . '"' ) . ' />' ) . '
  ' . ( '<' . 'meta' . ( ' name="' . ('viewport') . '"' . ' content="' . ('width=device-width, initial-scale=1') . '"' ) . ' />' ) . '
  ' . ( '<' . 'title' . ( '' ) . '>' . ( $eval->renderValue( ( $eval->truthy( ( ( is_array( $__v1 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v1[ 'title' ] ?? null ) : $eval->getProperty( $__v1, 'title' ) ) ) ) ? ( $eval->renderValue( ( ( is_array( $__v2 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'page' ) : $ctx->get( 'page' ) ) ) ) ? ( $__v2[ 'title' ] ?? null ) : $eval->getProperty( $__v2, 'title' ) ) ), $ctx ) . ' — ' . $eval->renderValue( ( ( is_array( $__v3 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'site' ) : $ctx->get( 'site' ) ) ) ) ? ( $__v3[ 'title' ] ?? null ) : $eval->getProperty( $__v3, 'title' ) ) ), $ctx ) ) : ( ( is_array( $__v4 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'site' ) : $ctx->get( 'site' ) ) ) ) ? ( $__v4[ 'title' ] ?? null ) : $eval->getProperty( $__v4, 'title' ) ) ) ), $ctx ) ) . '</' . 'title' . '>' ) . '
  ' . ( '<' . 'meta' . ( ' name="' . ('description') . '"' . $eval->attribute( 'content', ( ( is_array( $__v5 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'site' ) : $ctx->get( 'site' ) ) ) ) ? ( $__v5[ 'tagline' ] ?? null ) : $eval->getProperty( $__v5, 'tagline' ) ) ) ) ) . ' />' ) . '
  ' . ( '<' . 'link' . ( ' rel="' . ('stylesheet') . '"' . $eval->attribute( 'href', ( $eval->applyFilter( ('base.css'), 'asset_url', $ctx ) ) ) ) . ' />' ) . '
  ' . ( '<style>' . ('
    :root ' . '{' . '
      --accent: ' . $eval->renderValue( ( ( is_array( $__v6 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'settings' ) : $ctx->get( 'settings' ) ) ) ) ? ( $__v6[ 'color_accent' ] ?? null ) : $eval->getProperty( $__v6, 'color_accent' ) ) ), $ctx ) . ';
      --ink: ' . $eval->renderValue( ( ( is_array( $__v7 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'settings' ) : $ctx->get( 'settings' ) ) ) ) ? ( $__v7[ 'color_ink' ] ?? null ) : $eval->getProperty( $__v7, 'color_ink' ) ) ), $ctx ) . ';
      --measure: ' . $eval->renderValue( ( ( is_array( $__v8 = ( ( $ctx->strict ? $eval->identifier( $ctx, 'settings' ) : $ctx->get( 'settings' ) ) ) ) ? ( $__v8[ 'measure' ] ?? null ) : $eval->getProperty( $__v8, 'measure' ) ) ), $ctx ) . 'px;
    ' . '}' . '
  ') . '</style>' ) . '
' ) . '</' . 'head' . '>' ) . '
' . ( '<' . 'body' . ( '' ) . '>' . ( '
  ' . $eval->renderValue( ( $eval->callNamed( $ctx, 'section', [ ('header') ] ) ), $ctx ) . '
  ' . ( '<' . 'main' . ( ' id="' . ('main') . '"' ) . '>' . ( $eval->renderValue( ( ( $ctx->strict ? $eval->identifier( $ctx, 'content_for_layout' ) : $ctx->get( 'content_for_layout' ) ) ), $ctx ) ) . '</' . 'main' . '>' ) . '
  ' . $eval->renderValue( ( $eval->callNamed( $ctx, 'section', [ ('footer') ] ) ), $ctx ) . '
' ) . '</' . 'body' . '>' ) . '
' ) . '</' . 'html' . '>' );
        $out .= '
';
        if ( null !== $__v0 ) {
            $out .= '</' . $__v0 . '>';
        }
    } finally {
        $ctx->pop();
    }

    return $out;
};